### ISSUE TITLE
Sources / Links

### ISSUE THREAD

**Issue by MartinThoma** [kgullikson88/kgullikson88.github.io#1]
Hello Kevin,

reading your blog post http://kgullikson88.github.io/blog/pypi-analysis.html I have the impression that it is inspired (or at least related very much) to my post https://martin-thoma.com/analyzing-pypi-metadata-2/. You might want to link to it.

Best regards,
Martin

**Comment by kgullikson88** [comment]
Hi Martin,

I actually didn't see that post! The work was inspired by [Olivier Girardot's](https://ogirardot.wordpress.com/2013/01/05/state-of-the-pythonpypi-dependency-graph/) post from a few years ago, which I did link to. I'll go ahead and add a mention to your post as a related thing. Thanks for the heads up!

**Comment by MartinThoma** [comment]
Thank you very much. And thank you for your article / the pointer to http://ogirardot.github.io/meta-deps/ :-) It is interesting to see that there are people having similar ideas, similar ways to carry them out at almost the same time and independently from each other. 

Just FYI: I've also added a link to your article.
